/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 23/03/2022 08:28:56
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSIDIV_VALUE                         32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSICalibrationValue                  16
#define MX_HSE_VALUE                            16000000
#define MX_SYSCLKFreq_VALUE                     160000000
#define MX_HCLKFreq_Value                       160000000
#define MX_FCLKCortexFreq_Value                 160000000
#define MX_CortexFreq_Value                     160000000
#define MX_AHBFreq_Value                        160000000
#define MX_APB1Freq_Value                       160000000
#define MX_APB2Freq_Value                       160000000
#define MX_APB1TimFreq_Value                    160000000
#define MX_APB2TimFreq_Value                    160000000
#define MX_ADCFreq_Value                        16000000
#define MX_I2C1Freq_Value                       160000000
#define MX_I2C2Freq_Value                       160000000
#define MX_I2C3Freq_Value                       160000000
#define MX_MSI_VALUE                            4000000
#define MX_SPI1Freq_Value                       160000000
#define MX_SPI2Freq_Value                       160000000
#define MX_SPI3Freq_Value                       160000000
#define MX_USBFreq_Value                        48000000
#define MX_WatchDogFreq_Value                   32000
#define MX_LPTIM1Freq_Value                     4000000
#define MX_LPTIM2Freq_Value                     160000000
#define MX_RTCFreq_Value                        32000
#define MX_MCO1PinFreq_Value                    160000000
#define MX_CRSFreq_Value                        48000000
#define MX_SWPMI1Freq_Value                     4000000
#define MX_SAI1Freq_Value                       258000000
#define MX_SAI2Freq_Value                       258000000
#define MX_LPUART1Freq_Value                    160000000
#define MX_UART4Freq_Value                      160000000
#define MX_UART5Freq_Value                      160000000
#define MX_USART1Freq_Value                     160000000
#define MX_USART2Freq_Value                     160000000
#define MX_USART3Freq_Value                     160000000

/*-------------------------------- CORTEX_M33_NS --------------------------------*/

#define MX_CORTEX_M33_NS                        1

/*-------------------------------- I2C2       --------------------------------*/

#define MX_I2C2                                 1

/* GPIO Configuration */

/* Pin PH5 */
#define MX_I2C2_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SDA_Pin                         PH5
#define MX_I2C2_SDA_GPIOx                       GPIOH
#define MX_I2C2_SDA_GPIO_Pin                    GPIO_PIN_5
#define MX_I2C2_SDA_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SDA_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C2_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PH4 */
#define MX_I2C2_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SCL_Pin                         PH4
#define MX_I2C2_SCL_GPIOx                       GPIOH
#define MX_I2C2_SCL_GPIO_Pin                    GPIO_PIN_4
#define MX_I2C2_SCL_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SCL_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C2_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- ICACHE     --------------------------------*/

#define MX_ICACHE                               1

/*-------------------------------- PWR        --------------------------------*/

#define MX_PWR                                  1

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC13 */
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PE11 */
#define MX_PE11_Pin                             PE11
#define MX_PE11_GPIOx                           GPIOE
#define MX_PE11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE11_GPIO_Pin                        GPIO_PIN_11
#define MX_PE11_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PF11 */
#define MX_PF11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF11_Pin                             PF11
#define MX_PF11_GPIOx                           GPIOF
#define MX_PF11_PinState                        GPIO_PIN_RESET
#define MX_PF11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PF11_GPIO_Pin                        GPIO_PIN_11
#define MX_PF11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD9 */
#define MX_PD9_Pin                              PD9
#define MX_PD9_GPIOx                            GPIOD
#define MX_PD9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD9_GPIO_Pin                         GPIO_PIN_9
#define MX_PD9_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PD10 */
#define MX_PD10_Pin                             PD10
#define MX_PD10_GPIOx                           GPIOD
#define MX_PD10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PD10_GPIO_Pin                        GPIO_PIN_10
#define MX_PD10_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PG2 */
#define MX_PG2_Pin                              PG2
#define MX_PG2_GPIOx                            GPIOG
#define MX_PG2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG2_GPIO_Pin                         GPIO_PIN_2
#define MX_PG2_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PH7 */
#define MX_PH7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH7_Pin                              PH7
#define MX_PH7_GPIOx                            GPIOH
#define MX_PH7_PinState                         GPIO_PIN_SET
#define MX_PH7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH7_GPIO_Pin                         GPIO_PIN_7
#define MX_PH7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH1-OSC_OUT (PH1) */
#define MX_PH1_OSC_OUT_PH1_GPIO_Speed           GPIO_SPEED_FREQ_LOW
#define MX_PH1_OSC_OUT_PH1_Pin                  PH1_OSC_OUT_PH1
#define MX_PH1_OSC_OUT_PH1_GPIOx                GPIOH
#define MX_PH1_OSC_OUT_PH1_PinState             GPIO_PIN_RESET
#define MX_PH1_OSC_OUT_PH1_GPIO_PuPd            GPIO_NOPULL
#define MX_PH1_OSC_OUT_PH1_GPIO_Pin             GPIO_PIN_1
#define MX_PH1_OSC_OUT_PH1_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PH6 */
#define MX_PH6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH6_Pin                              PH6
#define MX_PH6_GPIOx                            GPIOH
#define MX_PH6_PinState                         GPIO_PIN_SET
#define MX_PH6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH6_GPIO_Pin                         GPIO_PIN_6
#define MX_PH6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG5 */
#define MX_PG5_Pin                              PG5
#define MX_PG5_GPIOx                            GPIOG
#define MX_PG5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG5_GPIO_Pin                         GPIO_PIN_5
#define MX_PG5_GPIO_Mode                        GPIO_MODE_INPUT

#endif  /* __MX_DEVICE_H */

